version: '3.8'
services:
  android-build:
    build:
      context: .
      dockerfile: Dockerfile.android
    container_name: android-kotlin-build
    volumes:
      - .:/workspace
      - gradle-cache:/root/.gradle
    working_dir: /workspace
    environment:
      - ANDROID_HOME=/opt/android-sdk
    command: ["./gradlew", "assembleDebug"]

  android-shell:
    build:
      context: .
      dockerfile: Dockerfile.android
    container_name: android-kotlin-shell
    volumes:
      - .:/workspace
      - gradle-cache:/root/.gradle
    working_dir: /workspace
    environment:
      - ANDROID_HOME=/opt/android-sdk
    command: ["sleep", "infinity"]
    stdin_open: true
    tty: true

volumes:
  gradle-cache: